# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 451b9e872bf5425225db29a4ae15a8fc07a9ba96d167779b2b60e4b4b5ac503e7740efca6c08cc1cead73b40818e94b559e5dad8bbc22cbeaa93aa4cb24bb948

test:
  secret_key_base: 386c5cbf1b731555e3c273adaf7ae526df70d89b766e3804b0370d58a4ff386f9b07dd56ae0227532600b9ef60a46073d2e7ccc2e47901b9c5ccb6e5229baac7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
